---
- hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/base_packages.yml
    - include: tasks/bash.yml
    - include: tasks/memoio.yml
    - include: tasks/teamviewer13.yml
    - include: tasks/ssh.yml
