---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml
  tasks:
    - include_tasks: tasks/base_packages.yml
    - include_tasks: tasks/bash.yml
    - include_tasks: tasks/ssh.yml
