---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.yml
  tasks:
    - include: tasks/base_packages.yml
    - include: tasks/bash.yml
    - include: tasks/ssh.yml
    - include: tasks/timemachine.yml
