---
- hosts: localhost
  user: scireum
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew

  tasks:
    - include: tasks/ansible-setup.yml
    - include: tasks/preferences.yml
    - include: tasks/oxomi.yml
    - include: tasks/basic.yml
