---

- name: "install bash_profile"
  copy:
    src: bash/bash_profile
    dest: ~/.bash_profile

- name: "install brew bash into allowed shells"
  lineinfile:
    path: /etc/shells
    state: present
    line: "/opt/homebrew/bin/bash"
    regexp: "^/opt/homebrew/bin/bash"
  become: yes
  become_method: sudo

- name: "set user shell to new brew bash"
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /opt/homebrew/bin/bash
  become: yes
  become_method: sudo
