---

- name: remove apple stuff from dock
  command: /usr/local/bin/dockutil --remove "{{ item }}"
  loop:
    - Siri
    - TV
    - Mail
    - FaceTime
    - Kalender
    - Karten
    - Musik
    - Kontakte
    - Erinnerungen
    - Launchpad
    - Notizen
    - Podcasts
    - Fotos
    - Nachrichten
    - Safari
    - 'App Store'

- name: add stuff to dock
  command: /usr/local/bin/dockutil --add {{ item }}
  loop:
    - /Applications/Firefox.app
    - /Applications/MEMOIO.app
