---

- name: "install script to query ssh config"
  copy:
    src: ssh/update-ssh-config
    dest: /usr/local/bin/update-ssh-config
    mode: 0755

- name: "install script to query sign ssh keys via hildeguard"
  copy:
    src: ssh/sign-keys
    dest: /usr/local/bin/sign-keys
    mode: 0755
