---

- name: "install /usr/local/bin"
  file:
    path: /usr/local/bin
    state: directory
  become: yes
  become_method: sudo

- name: "install bash symlink"
  file:
    dest: /usr/local/bin/bash
    src: /opt/homebrew/bin/bash
    state: link
  become: yes
  become_method: sudo

- name: "install script to query ssh config"
  copy:
    src: ssh/update-ssh-config
    dest: /usr/local/bin/update-ssh-config
    mode: 0755
  become: yes
  become_method: sudo

- name: "install .ssh directory for user"
  file:
    path: ~/.ssh
    state: directory

- name: "install default empty file config.footer"
  file:
    path: ~/.ssh/config.footer
    state: touch

- name: "install script to query sign ssh keys via hildeguard"
  copy:
    src: ssh/sign-keys
    dest: /usr/local/bin/sign-keys
    mode: 0755
  become: yes
  become_method: sudo
