---

- name: "install .ssh directory for user"
  file:
    path: ~/.ssh
    state: directory

- name: "install default empty file config.footer"
  file:
    path: ~/.ssh/config.footer
    state: touch

